// COMMENTS

export const COMMENT_SUBMITTED = 'COMMENT_SUBMITTED';
export const COMMENT_SUBMIT_FAILED = 'COMMENT_SUBMIT_FAILED';
export const COMMENT_SUBMIT_SUCCEEDED = 'COMMENT_SUBMIT_SUCCEEDED';

export const NEW_COMMENTS_ADDED = 'NEW_COMMENTS_ADDED';
