// SENTIMENT

export const SENTIMENT_UPDATED = 'SENTIMENT_UPDATED';

export const SENTIMENT_REQUESTED = 'SENTIMENT_REQUESTED';
export const SENTIMENT_REQUEST_FAILED = 'SENTIMENT_REQUEST_FAILED';
export const SENTIMENT_REQUEST_SUCCEEDED = 'SENTIMENT_REQUEST_SUCCEEDED';
export const INVALID_SENTIMENT_REQUESTED = 'INVALID_SENTIMENT_REQUESTED';

export const SENTIMENT_REMOVAL_REQUESTED = 'SENTIMENT_REMOVAL_REQUESTED';
export const SENTIMENT_REMOVAL_REQUEST_FAILED = 'SENTIMENT_REMOVAL_REQUEST_FAILED';
export const SENTIMENT_REMOVAL_REQUEST_SUCCEEDED = 'SENTIMENT_REMOVAL_REQUEST_SUCCEEDED';
export const INVALID_SENTIMENT_REMOVAL_REQUESTED = 'INVALID_SENTIMENT_REMOVAL_REQUESTED';
